
pipeline {
          
     agent any   
     
     tools {nodejs "mynodejs"}
     
     stages {
       
        stage("dev branch") {
             when { branch "main" }
            steps {
                sh " npm install"
                sh " npm run build"               
                  
             sshPublisher(publishers: [sshPublisherDesc(configName: 'react server', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/var/www/html/', remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'build/')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }contact.nikhilnambiar@gmail.com
        }


        stage("production branch") {
             when { branch "prod" }
            steps {
                sh " npm install"
                sh " npm run build"

             sshPublisher(publishers: [sshPublisherDesc(configName: 'react server', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/var/www/html/', remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'build/')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
       
    }
}

